#!/usr/bin/env python
import ctypes

SYSCALL_NUM = "rax"
SYSCALL_ARG_REGS = ["rdi", "rsi", "rdx", "r10", "r8", "r9"]
FPREGS_FIELDS = [
    ("cwd", ctypes.c_ushort),
    ("swd", ctypes.c_ushort),
    ("ftw", ctypes.c_ushort),
    ("fop", ctypes.c_ushort),
    ("rip",ctypes.c_ulonglong),
    ("rdp",ctypes.c_ulonglong),
    ("mxcsr", ctypes.c_uint),
    ("mask", ctypes.c_uint),
    ("st_space", ctypes.c_uint * 32),
    ("xmm_space", ctypes.c_uint * 64),
    ("padding", ctypes.c_uint * 24)]
REGS_FIELDS = (
    ("r15", ctypes.c_ulonglong),
    ("r14", ctypes.c_ulonglong),
    ("r13", ctypes.c_ulonglong),
    ("r12", ctypes.c_ulonglong),
    ("rbp", ctypes.c_ulonglong),
    ("rbx", ctypes.c_ulonglong),
    ("r11", ctypes.c_ulonglong),
    ("r10", ctypes.c_ulonglong),
    ("r9", ctypes.c_ulonglong),
    ("r8", ctypes.c_ulonglong),
    ("rax", ctypes.c_ulonglong),
    ("rcx", ctypes.c_ulonglong),
    ("rdx", ctypes.c_ulonglong),
    ("rsi", ctypes.c_ulonglong),
    ("rdi", ctypes.c_ulonglong),
    ("orig_rax", ctypes.c_ulonglong),
    ("rip", ctypes.c_ulonglong),
    ("cs", ctypes.c_ulonglong),
    ("eflags", ctypes.c_ulonglong),
    ("rsp", ctypes.c_ulonglong),
    ("ss", ctypes.c_ulonglong),
    ("fs_base", ctypes.c_ulonglong),
    ("gs_base", ctypes.c_ulonglong),
    ("ds", ctypes.c_ulonglong),
    ("es", ctypes.c_ulonglong),
    ("fs", ctypes.c_ulonglong),
    ("gs", ctypes.c_ulonglong))

SYSCALL_TABLE = [{'args': ['pid_t pid',
                           'const struct iovec *lvec',
                           'unsigned long liovcnt',
                           'const struct iovcc *rvec',
                           'unsigned long riovcnt',
                           'unsigned long flags'],
                  'number': '311',
                  'name': 'sys_process_vm_writev'},
                 {'args': ['pid_t pid',
                           'const struct iovec *lvec',
                           'unsigned long liovcnt',
                           'const struct iovec *rvec',
                           'unsigned long riovcnt',
                           'unsigned long flags'],
                  'number': '310',
                  'name': 'sys_process_vm_readv'},
                 {'args': ['unsigned *cpup', 
                           'unsigned *nodep',
                           'struct getcpu_cache *unused'],
                  'number': '309',
                  'name': 'sys_getcpu'},
                 {'args': ['int fd', 'int nstype'], 
                  'number': '308', 'name': 'sys_setns'},
                 {'args': ['int fd',
                           'struct mmsghdr *mmsg',
                           'unsigned int vlen',
                           'unsigned int flags'],
                  'number': '307',
                  'name': 'sys_sendmmsg'},
                 {'args': ['int fd'], 'number': '306', 'name': 'sys_syncfs'},
                 {'args': ['clockid_t which_clock', 'struct timex *tx'],
                  'number': '305',
                  'name': 'sys_clock_adjtime'},
                 {'args': ['int dfd',
                           'const char *name',
                           'struct file_handle *handle',
                           'int *mnt_id',
                           'int flags'],
                  'number': '304',
                  'name': 'sys_open_by_handle_at'},
                 {'args': ['int dfd',
                           'const char *name',
                           'struct file_handle *handle',
                           'int *mnt_id',
                           'int flag'],
                  'number': '303',
                  'name': 'sys_name_to_handle_at'},
                 {'args': ['pid_t pid',
                           'unsigned int resource',
                           'const struct rlimit64 *new_rlim',
                           'struct rlimit64 *old_rlim'],
                  'number': '302',
                  'name': 'sys_prlimit64'},
                 {'args': ['long fanotify_fd',
                           'long flags',
                           '__u64 mask',
                           'long dfd',
                           'long pathname'],
                  'number': '301',
                  'name': 'sys_fanotify_mark'},
                 {'args': ['unsigned int flags', 'unsigned int event_f_flags'],
                  'number': '300',
                  'name': 'sys_fanotify_init'},
                 {'args': ['int fd',
                           'struct msghdr *mmsg',
                           'unsigned int vlen',
                           'unsigned int flags',
                           'struct timespec *timeout'],
                  'number': '299',
                  'name': 'sys_recvmmsg'},
                 {'args': ['struct perf_event_attr *attr_uptr',
                           'pid_t pid',
                           'int cpu',
                           'int group_fd',
                           'unsigned long flags'],
                  'number': '298',
                  'name': 'sys_perf_event_open'},
                 {'args': ['pid_t tgid', 
                           'pid_t pid', 
                           'int sig', 
                           'siginfo_t *uinfo'],
                  'number': '297',
                  'name': 'sys_rt_tgsigqueueinfo'},
                 {'args': ['unsigned long fd',
                           'const struct iovec *vec',
                           'unsigned long vlen',
                           'unsigned long pos_l',
                           'unsigned long pos_h'],
                  'number': '296',
                  'name': 'sys_pwritev'},
                 {'args': ['unsigned long fd',
                           'const struct iovec *vec',
                           'unsigned long vlen',
                           'unsigned long pos_l',
                           'unsigned long pos_h'],
                  'number': '295',
                  'name': 'sys_preadv'},
                 {'args': ['int flags'], 
                  'number': '294', 
                  'name': 'sys_inotify_init1'},
                 {'args': ['int *filedes', 'int flags'],
                  'number': '293',
                  'name': 'sys_pipe2'},
                 {'args': ['unsigned int oldfd', 
                           'unsigned int newfd', 
                           'int flags'],
                  'number': '292',
                  'name': 'sys_dup3'},
                 {'args': ['int flags'], 
                  'number': '291', 
                  'name': 'sys_epoll_create1'},
                 {'args': ['unsigned int count', 'int flags'],
                  'number': '290',
                  'name': 'sys_eventfd2'},
                 {'args': ['int ufd', 
                           'sigset_t *user_mask',
                           'size_t sizemask',
                           'int flags'],
                  'number': '289',
                  'name': 'sys_signalfd4'},
                 {'args': ['int fd',
                           'struct sockaddr *upeer_sockaddr',
                           'int *upeer_addrlen',
                           'int flags'],
                  'number': '288',
                  'name': 'sys_accept4'},
                 {'args': ['int ufd', 'struct itimerspec *otmr'],
                  'number': '287',
                  'name': 'sys_timerfd_gettime'},
                 {'args': ['int ufd',
                           'int flags',
                           'const struct itimerspec *utmr',
                           'struct itimerspec *otmr'],
                  'number': '286',
                  'name': 'sys_timerfd_settime'},
                 {'args': ['long fd',
                           'long mode', 
                           'loff_t offset', 
                           'loff_t len'],
                  'number': '285',
                  'name': 'sys_fallocate'},
                 {'args': ['unsigned int count'], 
                  'number': '284', 'name': 'sys_eventfd'},
                 {'args': ['int clockid', 'int flags'],
                  'number': '283',
                  'name': 'sys_timerfd_create'},
                 {'args': ['int ufd', 
                           'sigset_t *user_mask', 
                           'size_t sizemask'],
                  'number': '282',
                  'name': 'sys_signalfd'},
                 {'args': ['int epfd',
                           'struct epoll_event *events',
                           'int maxevents',
                           'int timeout',
                           'const sigset_t *sigmask',
                           'size_t sigsetsize'],
                  'number': '281',
                  'name': 'sys_epoll_pwait'},
                 {'args': ['int dfd',
                           'const char *filename',
                           'struct timespec *utimes',
                           'int flags'],
                  'number': '280',
                  'name': 'sys_utimensat'},
                 {'args': ['pid_t pid',
                           'unsigned long nr_pages',
                           'const void **pages',
                           'const int *nodes',
                           'int *status',
                           'int flags'],
                  'number': '279',
                  'name': 'sys_move_pages'},
                 {'args': ['int fd',
                           'const struct iovec *iov',
                           'unsigned long nr_segs',
                           'unsigned int flags'],
                  'number': '278',
                  'name': 'sys_vmsplice'},
                 {'args': ['long fd', 
                           'loff_t offset', 
                           'loff_t bytes', 
                           'long flags'],
                  'number': '277',
                  'name': 'sys_sync_file_range'},
                 {'args': ['int fdin', 
                           'int fdout', 
                           'size_t len', 
                           'unsigned int flags'],
                  'number': '276',
                  'name': 'sys_tee'},
                 {'args': ['int fd_in',
                           'loff_t *off_in',
                           'int fd_out',
                           'loff_t *off_out',
                           'size_t len',
                           'unsigned int flags'],
                  'number': '275',
                  'name': 'sys_splice'},
                 {'args': ['int pid', 
                           'struct robust_list_head **head_ptr', 
                           'size_t *len_ptr'],
                  'number': '274',
                  'name': 'sys_get_robust_list'},
                 {'args': ['struct robust_list_head *head', 'size_t len'],
                  'number': '273',
                  'name': 'sys_set_robust_list'},
                 {'args': ['unsigned long unshare_flags'],
                  'number': '272',
                  'name': 'sys_unshare'},
                 {'args': ['struct pollfd *ufds',
                           'unsigned int nfds',
                           'struct timespec *tsp',
                           'const sigset_t *sigmask',
                           'size_t sigsetsize'],
                  'number': '271',
                  'name': 'sys_ppoll'},
                 {'args': ['int n',
                           'fd_set *inp',
                           'fd_set *outp',
                           'fd_set *exp',
                           'struct timespec *tsp',
                           'void *sig'],
                  'number': '270',
                  'name': 'sys_pselect6'},
                 {'args': ['int dfd', 'const char *filename', 'int mode'],
                  'number': '269',
                  'name': 'sys_faccessat'},
                 {'args': ['int dfd', 'const char *filename', 'mode_t mode'],
                  'number': '268',
                  'name': 'sys_fchmodat'},
                 {'args': ['int dfd',
                           'const char *pathname', 
                           'char *buf',
                           'int bufsiz'],
                  'number': '267',
                  'name': 'sys_readlinkat'},
                 {'args': ['const char *oldname',
                           'int newfd',
                           'const char *newname'],
                  'number': '266',
                  'name': 'sys_symlinkat'},
                 {'args': ['int oldfd',
                           'const char *oldname',
                           'int newfd',
                           'const char *newname',
                           'int flags'],
                  'number': '265',
                  'name': 'sys_linkat'},
                 {'args': ['int oldfd',
                           'const char *oldname',
                           'int newfd',
                           'const char *newname'],
                  'number': '264',
                  'name': 'sys_renameat'},
                 {'args': ['int dfd', 'const char *pathname', 'int flag'],
                  'number': '263',
                  'name': 'sys_unlinkat'},
                 {'args': ['int dfd',
                           'const char *filename',
                           'struct stat *statbuf',
                           'int flag'],
                  'number': '262',
                  'name': 'sys_newfstatat'},
                 {'args': ['int dfd',
                           'const char *filename',
                           'struct timeval *utimes'],
                  'number': '261',
                  'name': 'sys_futimesat'},
                 {'args': ['int dfd',
                           'const char *filename',
                           'uid_t user',
                           'gid_t group',
                           'int flag'],
                  'number': '260',
                  'name': 'sys_fchownat'},
                 {'args': ['int dfd',
                           'const char *filename',
                           'int mode',
                           'unsigned dev'],
                  'number': '259',
                  'name': 'sys_mknodat'},
                 {'args': ['int dfd', 'const char *pathname', 'int mode'],
                  'number': '258',
                  'name': 'sys_mkdirat'},
                 {'args': ['int dfd',
                           'const char *filename',
                           'int flags',
                           'int mode'],
                  'number': '257',
                  'name': 'sys_openat'},
                 {'args': ['pid_t pid',
                           'unsigned long maxnode',
                           'const unsigned long *old_nodes',
                           'const unsigned long *new_nodes'],
                  'number': '256',
                  'name': 'sys_migrate_pages'},
                 {'args': ['int fd', '__s32 wd'],
                  'number': '255',
                  'name': 'sys_inotify_rm_watch'},
                 {'args': ['int fd', 'const char *pathname', 'u32 mask'],
                  'number': '254',
                  'name': 'sys_inotify_add_watch'},
                 {'args': [], 'number': '253', 'name': 'sys_inotify_init'},
                 {'args': ['int which', 'int who'],
                  'number': '252',
                  'name': 'sys_ioprio_get'},
                 {'args': ['int which', 'int who', 'int ioprio'],
                  'number': '251',
                  'name': 'sys_ioprio_set'},
                 {'args': ['int option',
                           'unsigned long arg2',
                           'unsigned long arg3',
                           'unsigned long arg4',
                           'unsigned long arg5'],
                  'number': '250',
                  'name': 'sys_keyctl'},
                 {'args': ['const char *_type',
                           'const char *_description',
                           'const char *_callout_info',
                           'key_serial_t destringid'],
                  'number': '249',
                  'name': 'sys_request_key'},
                 {'args': ['const char *_type',
                           'const char *_description',
                           'const void *_payload',
                           'size_t plen'],
                  'number': '248',
                  'name': 'sys_add_key'},
                 {'args': ['int which',
                           'pid_t upid',
                           'struct siginfo *infop',
                           'int options',
                           'struct rusage *ru'],
                  'number': '247',
                  'name': 'sys_waitid'},
                 {'args': ['unsigned long entry',
                           'unsigned long nr_segments',
                           'struct kexec_segment *segments',
                           'unsigned long flags'],
                  'number': '246',
                  'name': 'sys_kexec_load'},
                 {'args': ['mqd_t mqdes',
                           'const struct mq_attr *u_mqstat',
                           'struct mq_attr *u_omqstat'],
                  'number': '245',
                  'name': 'sys_mq_getsetattr'},
                 {'args': ['mqd_t mqdes', 'const struct sigevent *u_notification'],
                  'number': '244',
                  'name': 'sys_mq_notify'},
                 {'args': ['mqd_t mqdes',
                           'char *u_msg_ptr',
                           'size_t msg_len',
                           'unsigned int *u_msg_prio',
                           'const struct timespec *u_abs_timeout'],
                  'number': '243',
                  'name': 'sys_mq_timedreceive'},
                 {'args': ['mqd_t mqdes',
                           'const char *u_msg_ptr',
                           'size_t msg_len',
                           'unsigned int msg_prio',
                           'const stuct timespec *u_abs_timeout'],
                  'number': '242',
                  'name': 'sys_mq_timedsend'},
                 {'args': ['const char *u_name'], 'number': '241', 'name': 'sys_mq_unlink'},
                 {'args': ['const char *u_name',
                           'int oflag',
                           'mode_t mode',
                           'struct mq_attr *u_attr'],
                  'number': '240',
                  'name': 'sys_mq_open'},
                 {'args': ['int *policy',
                           'unsigned long *nmask',
                           'unsigned long maxnode',
                           'unsigned long addr',
                           'unsigned long flags'],
                  'number': '239',
                  'name': 'sys_get_mempolicy'},
                 {'args': ['int mode', 'unsigned long *nmask', 'unsigned long maxnode'],
                  'number': '238',
                  'name': 'sys_set_mempolicy'},
                 {'args': ['unsigned long start',
                           'unsigned long len',
                           'unsigned long mode',
                           'unsigned long *nmask',
                           'unsigned long maxnode',
                           'unsigned flags'],
                  'number': '237',
                  'name': 'sys_mbind'},
                 {'args': ['NOT IMPLEMENTED'], 'number': '236', 'name': 'sys_vserver'},
                 {'args': ['char *filename', 'struct timeval *utimes'],
                  'number': '235',
                  'name': 'sys_utimes'},
                 {'args': ['pid_t tgid', 'pid_t pid', 'int sig'],
                  'number': '234',
                  'name': 'sys_tgkill'},
                 {'args': ['int epfd', 'int op', 'int fd', 'struct epoll_event *event'],
                  'number': '233',
                  'name': 'sys_epoll_ctl'},
                 {'args': ['int epfd',
                           'struct epoll_event *events',
                           'int maxevents',
                           'int timeout'],
                  'number': '232',
                  'name': 'sys_epoll_wait'},
                 {'args': ['int error_code'], 'number': '231', 'name': 'sys_exit_group'},
                 {'args': ['const clockid_t which_clock',
                           'int flags',
                           'const struct timespec *rqtp',
                           'struct timespec *rmtp'],
                  'number': '230',
                  'name': 'sys_clock_nanosleep'},
                 {'args': ['const clockid_t which_clock', 'struct timespec *tp'],
                  'number': '229',
                  'name': 'sys_clock_getres'},
                 {'args': ['const clockid_t which_clock', 'struct timespec *tp'],
                  'number': '228',
                  'name': 'sys_clock_gettime'},
                 {'args': ['const clockid_t which_clock', 'const struct timespec *tp'],
                  'number': '227',
                  'name': 'sys_clock_settime'},
                 {'args': ['timer_t timer_id'], 'number': '226', 'name': 'sys_timer_delete'},
                 {'args': ['timer_t timer_id'],
                  'number': '225',
                  'name': 'sys_timer_getoverrun'},
                 {'args': ['timer_t timer_id', 'struct itimerspec *setting'],
                  'number': '224',
                  'name': 'sys_timer_gettime'},
                 {'args': ['timer_t timer_id',
                           'int flags',
                           'const struct itimerspec *new_setting',
                           'struct itimerspec *old_setting'],
                  'number': '223',
                  'name': 'sys_timer_settime'},
                 {'args': ['const clockid_t which_clock',
                           'struct sigevent *timer_event_spec',
                           'timer_t *created_timer_id'],
                  'number': '222',
                  'name': 'sys_timer_create'},
                 {'args': ['int fd', 'loff_t offset', 'size_t len', 'int advice'],
                  'number': '221',
                  'name': 'sys_fadvise64'},
                 {'args': ['int semid',
                           'struct sembuf *tsops',
                           'unsigned nsops',
                           'const struct timespec *timeout'],
                  'number': '220',
                  'name': 'sys_semtimedop'},
                 {'args': [], 'number': '219', 'name': 'sys_restart_syscall'},
                 {'args': ['int *tidptr'], 'number': '218', 'name': 'sys_set_tid_address'},
                 {'args': ['unsigned int fd',
                           'struct linux_dirent64 *dirent',
                           'unsigned int count'],
                  'number': '217',
                  'name': 'sys_getdents64'},
                 {'args': ['unsigned long start',
                           'unsigned long size',
                           'unsigned long prot',
                           'unsigned long pgoff',
                           'unsigned long flags'],
                  'number': '216',
                  'name': 'sys_remap_file_pages'},
                 {'args': ['NOT IMPLEMENTED'],
                  'number': '215',
                  'name': 'sys_epoll_wait_old'},
                 {'args': ['NOT IMPLEMENTED'], 'number': '214', 'name': 'sys_epoll_ctl_old'},
                 {'args': ['int size'], 'number': '213', 'name': 'sys_epoll_create'},
                 {'args': ['u64 cookie64', 'long buf', 'long len'],
                  'number': '212',
                  'name': 'sys_lookup_dcookie'},
                 {'args': ['NOT IMPLEMENTED. Use arch_prctl'],
                  'number': '211',
                  'name': 'sys_get_thread_area'},
                 {'args': ['aio_context_t ctx_id',
                           'struct iocb *iocb',
                           'struct io_event *result'],
                  'number': '210',
                  'name': 'sys_io_cancel'},
                 {'args': ['aio_context_t ctx_id', 'long nr', 'struct iocb **iocbpp'],
                  'number': '209',
                  'name': 'sys_io_submit'},
                 {'args': ['aio_context_t ctx_id',
                           'long min_nr',
                           'long nr',
                           'struct io_event *events'],
                  'number': '208',
                  'name': 'sys_io_getevents'},
                 {'args': ['aio_context_t ctx'], 'number': '207', 'name': 'sys_io_destroy'},
                 {'args': ['unsigned nr_events', 'aio_context_t *ctxp'],
                  'number': '206',
                  'name': 'sys_io_setup'},
                 {'args': ['NOT IMPLEMENTED. Use arch_prctl'],
                  'number': '205',
                  'name': 'sys_set_thread_area'},
                 {'args': ['pid_t pid', 'unsigned int len', 'unsigned long *user_mask_ptr'],
                  'number': '204',
                  'name': 'sys_sched_getaffinity'},
                 {'args': ['pid_t pid', 'unsigned int len', 'unsigned long *user_mask_ptr'],
                  'number': '203',
                  'name': 'sys_sched_setaffinity'},
                 {'args': ['u32 *uaddr',
                           'int op',
                           'u32 val',
                           'struct timespec *utime',
                           'u32 *uaddr2',
                           'u32 val3'],
                  'number': '202',
                  'name': 'sys_futex'},
                 {'args': ['time_t *tloc'], 'number': '201', 'name': 'sys_time'},
                 {'args': ['pid_t pid', 'ing sig'], 'number': '200', 'name': 'sys_tkill'},
                 {'args': ['int fd', 'const char *name'],
                  'number': '199',
                  'name': 'sys_fremovexattr'},
                 {'args': ['const char *pathname', 'const char *name'],
                  'number': '198',
                  'name': 'sys_lremovexattr'},
                 {'args': ['const char *pathname', 'const char *name'],
                  'number': '197',
                  'name': 'sys_removexattr'},
                 {'args': ['int fd', 'char *list', 'size_t size'],
                  'number': '196',
                  'name': 'sys_flistxattr'},
                 {'args': ['const char *pathname', 'char *list', 'size_t size'],
                  'number': '195',
                  'name': 'sys_llistxattr'},
                 {'args': ['const char *pathname', 'char *list', 'size_t size'],
                  'number': '194',
                  'name': 'sys_listxattr'},
                 {'args': ['int fd', 'const har *name', 'void *value', 'size_t size'],
                  'number': '193',
                  'name': 'sys_fgetxattr'},
                 {'args': ['const char *pathname',
                           'const char *name',
                           'void *value',
                           'size_t size'],
                  'number': '192',
                  'name': 'sys_lgetxattr'},
                 {'args': ['const char *pathname',
                           'const char *name',
                           'void *value',
                           'size_t size'],
                  'number': '191',
                  'name': 'sys_getxattr'},
                 {'args': ['int fd',
                           'const char *name',
                           'const void *value',
                           'size_t size',
                           'int flags'],
                  'number': '190',
                  'name': 'sys_fsetxattr'},
                 {'args': ['const char *pathname',
                           'const char *name',
                           'const void *value',
                           'size_t size',
                           'int flags'],
                  'number': '189',
                  'name': 'sys_lsetxattr'},
                 {'args': ['const char *pathname',
                           'const char *name',
                           'const void *value',
                           'size_t size',
                           'int flags'],
                  'number': '188',
                  'name': 'sys_setxattr'},
                 {'args': ['int fd', 'loff_t offset', 'size_t count'],
                  'number': '187',
                  'name': 'sys_readahead'},
                 {'args': [], 'number': '186', 'name': 'sys_gettid'},
                 {'args': ['NOT IMPLEMENTED'], 'number': '185', 'name': 'sys_security'},
                 {'args': ['NOT IMPLEMENTED'], 'number': '184', 'name': 'sys_tuxcall'},
                 {'args': ['NOT IMPLEMENTED'], 'number': '183', 'name': 'sys_afs_syscall'},
                 {'args': ['NOT IMPLEMENTED'], 'number': '182', 'name': 'sys_putpmsg'},
                 {'args': ['NOT IMPLEMENTED'], 'number': '181', 'name': 'sys_getpmsg'},
                 {'args': ['NOT IMPLEMENTED'], 'number': '180', 'name': 'sys_nfsservctl'},
                 {'args': ['unsigned int cmd',
                           'const char *special',
                           'qid_t id',
                           'void *addr'],
                  'number': '179',
                  'name': 'sys_quotactl'},
                 {'args': ['REMOVED IN Linux 2.6'],
                  'number': '178',
                  'name': 'sys_query_module'},
                 {'args': ['REMOVED IN Linux 2.6'],
                  'number': '177',
                  'name': 'sys_get_kernel_syms'},
                 {'args': ['const chat *name_user', 'unsigned int flags'],
                  'number': '176',
                  'name': 'sys_delete_module'},
                 {'args': ['void *umod', 'unsigned long len', 'const char *uargs'],
                  'number': '175',
                  'name': 'sys_init_module'},
                 {'args': ['REMOVED IN Linux 2.6'],
                  'number': '174',
                  'name': 'sys_create_module'},
                 {'args': ['unsigned long from', 'unsigned long num', 'int turn_on'],
                  'number': '173',
                  'name': 'sys_ioperm'},
                 {'args': ['unsigned int level', 'struct pt_regs *regs'],
                  'number': '172',
                  'name': 'sys_iopl'},
                 {'args': ['char *name', 'int len'],
                  'number': '171',
                  'name': 'sys_setdomainname'},
                 {'args': ['char *name', 'int len'],
                  'number': '170',
                  'name': 'sys_sethostname'},
                 {'args': ['int magic1', 'int magic2', 'unsigned int cmd', 'void *arg'],
                  'number': '169',
                  'name': 'sys_reboot'},
                 {'args': ['const char *specialfile'],
                  'number': '168',
                  'name': 'sys_swapoff'},
                 {'args': ['const char *specialfile', 'int swap_flags'],
                  'number': '167',
                  'name': 'sys_swapon'},
                 {'args': ['const char *target', 'int flags'],
                  'number': '166',
                  'name': 'sys_umount2'},
                 {'args': ['char *dev_name',
                           'char *dir_name',
                           'char *type',
                           'unsigned long flags',
                           'void *data'],
                  'number': '165',
                  'name': 'sys_mount'},
                 {'args': ['struct timeval *tv', 'struct timezone *tz'],
                  'number': '164',
                  'name': 'sys_settimeofday'},
                 {'args': ['const char *name'], 'number': '163', 'name': 'sys_acct'},
                 {'args': [], 'number': '162', 'name': 'sys_sync'},
                 {'args': ['const char *filename'], 'number': '161', 'name': 'sys_chroot'},
                 {'args': ['unsigned int resource', 'struct rlimit *rlim'],
                  'number': '160',
                  'name': 'sys_setrlimit'},
                 {'args': ['struct timex *txc_p'], 'number': '159', 'name': 'sys_adjtimex'},
                 {'args': ['struct task_struct *task', 'int code', 'unsigned long *addr'],
                  'number': '158',
                  'name': 'sys_arch_prctl'},
                 {'args': ['int option',
                           'unsigned long arg2',
                           'unsigned long arg3',
                           'unsigned long arg4',
                           'unsigned long arg5'],
                  'number': '157',
                  'name': 'sys_prctl'},
                 {'args': ['struct __sysctl_args *args'],
                  'number': '156',
                  'name': 'sys__sysctl'},
                 {'args': ['const char *new_root', 'const char *put_old'],
                  'number': '155',
                  'name': 'sys_pivot_root'},
                 {'args': ['int func', 'void *ptr', 'unsigned long bytecount'],
                  'number': '154',
                  'name': 'sys_modify_ldt'},
                 {'args': [], 'number': '153', 'name': 'sys_vhangup'},
                 {'args': [], 'number': '152', 'name': 'sys_munlockall'},
                 {'args': ['int flags'], 'number': '151', 'name': 'sys_mlockall'},
                 {'args': ['unsigned long start', 'size_t len'],
                  'number': '150',
                  'name': 'sys_munlock'},
                 {'args': ['unsigned long start', 'size_t len'],
                  'number': '149',
                  'name': 'sys_mlock'},
                 {'args': ['pid_t pid', 'struct timespec *interval'],
                  'number': '148',
                  'name': 'sys_sched_rr_get_interval'},
                 {'args': ['int policy'],
                  'number': '147',
                  'name': 'sys_sched_get_priority_min'},
                 {'args': ['int policy'],
                  'number': '146',
                  'name': 'sys_sched_get_priority_max'},
                 {'args': ['pid_t pid'], 'number': '145', 'name': 'sys_sched_getscheduler'},
                 {'args': ['pid_t pid', 'int policy', 'struct sched_param *param'],
                  'number': '144',
                  'name': 'sys_sched_setscheduler'},
                 {'args': ['pid_t pid', 'struct sched_param *param'],
                  'number': '143',
                  'name': 'sys_sched_getparam'},
                 {'args': ['pid_t pid', 'struct sched_param *param'],
                  'number': '142',
                  'name': 'sys_sched_setparam'},
                 {'args': ['int which', 'int who', 'int niceval'],
                  'number': '141',
                  'name': 'sys_setpriority'},
                 {'args': ['int which', 'int who'],
                  'number': '140',
                  'name': 'sys_getpriority'},
                 {'args': ['int option', 'unsigned long arg1', 'unsigned long arg2'],
                  'number': '139',
                  'name': 'sys_sysfs'},
                 {'args': ['unsigned int fd', 'struct statfs *buf'],
                  'number': '138',
                  'name': 'sys_fstatfs'},
                 {'args': ['const char *pathname', 'struct statfs *buf'],
                  'number': '137',
                  'name': 'sys_statfs'},
                 {'args': ['unsigned dev', 'struct ustat *ubuf'],
                  'number': '136',
                  'name': 'sys_ustat'},
                 {'args': ['unsigned int personality'],
                  'number': '135',
                  'name': 'sys_personality'},
                 {'args': ['NOT IMPLEMENTED'], 'number': '134', 'name': 'sys_uselib'},
                 {'args': ['const char *filename', 'int mode', 'unsigned dev'],
                  'number': '133',
                  'name': 'sys_mknod'},
                 {'args': ['char *filename', 'struct utimbuf *times'],
                  'number': '132',
                  'name': 'sys_utime'},
                 {'args': ['const stack_t *uss', 'stack_t *uoss'],
                  'number': '131',
                  'name': 'sys_sigaltstack'},
                 {'args': ['sigset_t *unewset', 'size_t sigsetsize'],
                  'number': '130',
                  'name': 'sys_rt_sigsuspend'},
                 {'args': ['pid_t pid', 'int sig', 'siginfo_t *uinfo'],
                  'number': '129',
                  'name': 'sys_rt_sigqueueinfo'},
                 {'args': ['const sigset_t *uthese',
                           'siginfo_t *uinfo',
                           'const struct timespec *uts',
                           'size_t sigsetsize'],
                  'number': '128',
                  'name': 'sys_rt_sigtimedwait'},
                 {'args': ['sigset_t *set', 'size_t sigsetsize'],
                  'number': '127',
                  'name': 'sys_rt_sigpending'},
                 {'args': ['cap_user_header_t header', 'const cap_user_data_t data'],
                  'number': '126',
                  'name': 'sys_capset'},
                 {'args': ['cap_user_header_t header', 'cap_user_data_t dataptr'],
                  'number': '125',
                  'name': 'sys_capget'},
                 {'args': ['pid_t pid'], 'number': '124', 'name': 'sys_getsid'},
                 {'args': ['gid_t gid'], 'number': '123', 'name': 'sys_setfsgid'},
                 {'args': ['uid_t uid'], 'number': '122', 'name': 'sys_setfsuid'},
                 {'args': ['pid_t pid'], 'number': '121', 'name': 'sys_getpgid'},
                 {'args': ['git_t *rgid', 'git_t *egid', 'git_t *sgid'],
                  'number': '120',
                  'name': 'sys_getresgid'},
                 {'args': ['gid_t rgid', 'gid_t egid', 'gid_t sgid'],
                  'number': '119',
                  'name': 'sys_setresgid'},
                 {'args': ['uid_t *ruid', 'uid_t *euid', 'uid_t *suid'],
                  'number': '118',
                  'name': 'sys_getresuid'},
                 {'args': ['uid_t *ruid', 'uid_t *euid', 'uid_t *suid'],
                  'number': '117',
                  'name': 'sys_setresuid'},
                 {'args': ['int gidsetsize', 'gid_t *grouplist'],
                  'number': '116',
                  'name': 'sys_setgroups'},
                 {'args': ['int gidsetsize', 'gid_t *grouplist'],
                  'number': '115',
                  'name': 'sys_getgroups'},
                 {'args': ['git_t rgid', 'gid_t egid'],
                  'number': '114',
                  'name': 'sys_setregid'},
                 {'args': ['uid_t ruid', 'uid_t euid'],
                  'number': '113',
                  'name': 'sys_setreuid'},
                 {'args': [], 'number': '112', 'name': 'sys_setsid'},
                 {'args': [], 'number': '111', 'name': 'sys_getpgrp'},
                 {'args': [], 'number': '110', 'name': 'sys_getppid'},
                 {'args': ['pid_t pid', 'pid_t pgid'],
                  'number': '109',
                  'name': 'sys_setpgid'},
                 {'args': [], 'number': '108', 'name': 'sys_getegid'},
                 {'args': [], 'number': '107', 'name': 'sys_geteuid'},
                 {'args': ['git_t gid'], 'number': '106', 'name': 'sys_setgid'},
                 {'args': ['uid_t uid'], 'number': '105', 'name': 'sys_setuid'},
                 {'args': [], 'number': '104', 'name': 'sys_getgid'},
                 {'args': ['int type', 'char *buf', 'int len'],
                  'number': '103',
                  'name': 'sys_syslog'},
                 {'args': [], 'number': '102', 'name': 'sys_getuid'},
                 {'args': ['long request',
                           'long pid',
                           'unsigned long addr',
                           'unsigned long data'],
                  'number': '101',
                  'name': 'sys_ptrace'},
                 {'args': ['struct sysinfo *info'], 'number': '100', 'name': 'sys_times'},
                 {'args': ['struct sysinfo *info'], 'number': '99', 'name': 'sys_sysinfo'},
                 {'args': ['int who', 'struct rusage *ru'],
                  'number': '98',
                  'name': 'sys_getrusage'},
                 {'args': ['unsigned int resource', 'struct rlimit *rlim'],
                  'number': '97',
                  'name': 'sys_getrlimit'},
                 {'args': ['struct timeval *tv', 'struct timezone *tz'],
                  'number': '96',
                  'name': 'sys_gettimeofday'},
                 {'args': ['int mask'], 'number': '95', 'name': 'sys_umask'},
                 {'args': ['const char *filename', 'uid_t user', 'git_t group'],
                  'number': '94',
                  'name': 'sys_lchown'},
                 {'args': ['unsigned int fd', 'uid_t user', 'git_t group'],
                  'number': '93',
                  'name': 'sys_fchown'},
                 {'args': ['const char *filename', 'uid_t user', 'git_t group'],
                  'number': '92',
                  'name': 'sys_chown'},
                 {'args': ['unsigned int fd', 'mode_t mode'],
                  'number': '91',
                  'name': 'sys_fchmod'},
                 {'args': ['const char *filename', 'mode_t mode'],
                  'number': '90',
                  'name': 'sys_chmod'},
                 {'args': ['const char *path', 'char *buf', 'int bufsiz'],
                  'number': '89',
                  'name': 'sys_readlink'},
                 {'args': ['const char *oldname', 'const char *newname'],
                  'number': '88',
                  'name': 'sys_symlink'},
                 {'args': ['const char *pathname'], 'number': '87', 'name': 'sys_unlink'},
                 {'args': ['const char *oldname', 'const char *newname'],
                  'number': '86',
                  'name': 'sys_link'},
                 {'args': ['const char *pathname', 'int mode'],
                  'number': '85',
                  'name': 'sys_creat'},
                 {'args': ['const char *pathname'], 'number': '84', 'name': 'sys_rmdir'},
                 {'args': ['const char *pathname', 'int mode'],
                  'number': '83',
                  'name': 'sys_mkdir'},
                 {'args': ['const char *oldname', 'const char *newname'],
                  'number': '82',
                  'name': 'sys_rename'},
                 {'args': ['unsigned int fd'], 'number': '81', 'name': 'sys_fchdir'},
                 {'args': ['const char *filename'], 'number': '80', 'name': 'sys_chdir'},
                 {'args': ['char *buf', 'unsigned long size'],
                  'number': '79',
                  'name': 'sys_getcwd'},
                 {'args': ['unsigned int fd',
                           'struct linux_dirent *dirent',
                           'unsigned int count'],
                  'number': '78',
                  'name': 'sys_getdents'},
                 {'args': ['unsigned int fd', 'unsigned long length'],
                  'number': '77',
                  'name': 'sys_ftruncate'},
                 {'args': ['const char *path', 'long length'],
                  'number': '76',
                  'name': 'sys_truncate'},
                 {'args': ['unsigned int fd'], 'number': '75', 'name': 'sys_fdatasync'},
                 {'args': ['unsigned int fd'], 'number': '74', 'name': 'sys_fsync'},
                 {'args': ['unsigned int fd', 'unsigned int cmd'],
                  'number': '73',
                  'name': 'sys_flock'},
                 {'args': ['unsigned int fd', 'unsigned int cmd', 'unsigned long arg'],
                  'number': '72',
                  'name': 'sys_fcntl'},
                 {'args': ['int msqid', 'int cmd', 'struct msqid_ds *buf'],
                  'number': '71',
                  'name': 'sys_msgctl'},
                 {'args': ['int msqid',
                           'struct msgbuf *msgp',
                           'size_t msgsz',
                           'long msgtyp',
                           'int msgflg'],
                  'number': '70',
                  'name': 'sys_msgrcv'},
                 {'args': ['int msqid', 'struct msgbuf *msgp', 'size_t msgsz', 'int msgflg'],
                  'number': '69',
                  'name': 'sys_msgsnd'},
                 {'args': ['key_t key', 'int msgflg'], 'number': '68', 'name': 'sys_msgget'},
                 {'args': ['char *shmaddr'], 'number': '67', 'name': 'sys_shmdt'},
                 {'args': ['int semid', 'int semnum', 'int cmd', 'union semun arg'],
                  'number': '66',
                  'name': 'sys_semctl'},
                 {'args': ['int semid', 'struct sembuf *tsops', 'unsigned nsops'],
                  'number': '65',
                  'name': 'sys_semop'},
                 {'args': ['key_t key', 'int nsems', 'int semflg'],
                  'number': '64',
                  'name': 'sys_semget'},
                 {'args': ['struct old_utsname *name'], 'number': '63', 'name': 'sys_uname'},
                 {'args': ['pid_t pid', 'int sig'], 'number': '62', 'name': 'sys_kill'},
                 {'args': ['pid_t upid', 'int *stat_addr', 'int options', 'struct rusage *ru'],
                  'number': '61',
                  'name': 'sys_wait4'},
                 {'args': ['int error_code'], 'number': '60', 'name': 'sys_exit'},
                 {'args': ['const char *filename',
                           'const char *const argv[]',
                           'const char *const envp[]'],
                  'number': '59',
                  'name': 'sys_execve'},
                 {'args': [], 'number': '58', 'name': 'sys_vfork'},
                 {'args': [], 'number': '57', 'name': 'sys_fork'},
                 {'args': ['unsigned long clone_flags',
                           'unsigned long newsp',
                           'void *parent_tid',
                           'void *child_tid'],
                  'number': '56',
                  'name': 'sys_clone'},
                 {'args': ['int fd',
                           'int level',
                           'int optname',
                           'char *optval',
                           'int *optlen'],
                  'number': '55',
                  'name': 'sys_getsockopt'},
                 {'args': ['int fd', 'int level', 'int optname', 'char *optval', 'int optlen'],
                  'number': '54',
                  'name': 'sys_setsockopt'},
                 {'args': ['int family', 'int type', 'int protocol', 'int *usockvec'],
                  'number': '53',
                  'name': 'sys_socketpair'},
                 {'args': ['int fd', 'struct sockaddr *usockaddr', 'int *usockaddr_len'],
                  'number': '52',
                  'name': 'sys_getpeername'},
                 {'args': ['int fd', 'struct sockaddr *usockaddr', 'int *usockaddr_len'],
                  'number': '51',
                  'name': 'sys_getsockname'},
                 {'args': ['int fd', 'int backlog'], 'number': '50', 'name': 'sys_listen'},
                 {'args': ['int fd', 'struct sokaddr *umyaddr', 'int addrlen'],
                  'number': '49',
                  'name': 'sys_bind'},
                 {'args': ['int fd', 'int how'], 'number': '48', 'name': 'sys_shutdown'},
                 {'args': ['int fd', 'struct msghdr *msg', 'unsigned int flags'],
                  'number': '47',
                  'name': 'sys_recvmsg'},
                 {'args': ['int fd', 'struct msghdr *msg', 'unsigned flags'],
                  'number': '46',
                  'name': 'sys_sendmsg'},
                 {'args': ['int fd',
                           'void *ubuf',
                           'size_t size',
                           'unsigned flags',
                           'struct sockaddr *addr',
                           'int *addr_len'],
                  'number': '45',
                  'name': 'sys_recvfrom'},
                 {'args': ['int fd',
                           'void *buff',
                           'size_t len',
                           'unsigned flags',
                           'struct sockaddr *addr',
                           'int addr_len'],
                  'number': '44',
                  'name': 'sys_sendto'},
                 {'args': ['int fd', 'struct sockaddr *upeer_sockaddr', 'int *upeer_addrlen'],
                  'number': '43',
                  'name': 'sys_accept'},
                 {'args': ['int fd', 'struct sockaddr *uservaddr', 'int addrlen'],
                  'number': '42',
                  'name': 'sys_connect'},
                 {'args': ['int family', 'int type', 'int protocol'],
                  'number': '41',
                  'name': 'sys_socket'},
                 {'args': ['int out_fd', 'int in_fd', 'off_t *offset', 'size_t count'],
                  'number': '40',
                  'name': 'sys_sendfile'},
                 {'args': [], 'number': '39', 'name': 'sys_getpid'},
                 {'args': ['int which', 'struct itimerval *value', 'struct itimerval *ovalue'],
                  'number': '38',
                  'name': 'sys_setitimer'},
                 {'args': ['unsigned int seconds'], 'number': '37', 'name': 'sys_alarm'},
                 {'args': ['int which', 'struct itimerval *value'],
                  'number': '36',
                  'name': 'sys_getitimer'},
                 {'args': ['struct timespec *rqtp', 'struct timespec *rmtp'],
                  'number': '35',
                  'name': 'sys_nanosleep'},
                 {'args': [], 'number': '34', 'name': 'sys_pause'},
                 {'args': ['unsigned int oldfd', 'unsigned int newfd'],
                  'number': '33',
                  'name': 'sys_dup2'},
                 {'args': ['unsigned int fildes'], 'number': '32', 'name': 'sys_dup'},
                 {'args': ['int shmid', 'int cmd', 'struct shmid_ds *buf'],
                  'number': '31',
                  'name': 'sys_shmctl'},
                 {'args': ['int shmid', 'char *shmaddr', 'int shmflg'],
                  'number': '30',
                  'name': 'sys_shmat'},
                 {'args': ['key_t key', 'size_t size', 'int shmflg'],
                  'number': '29',
                  'name': 'sys_shmget'},
                 {'args': ['unsigned long start', 'size_t len_in', 'int behavior'],
                  'number': '28',
                  'name': 'sys_madvise'},
                 {'args': ['unsigned long start', 'size_t len', 'unsigned char *vec'],
                  'number': '27',
                  'name': 'sys_mincore'},
                 {'args': ['unsigned long start', 'size_t len', 'int flags'],
                  'number': '26',
                  'name': 'sys_msync'},
                 {'args': ['unsigned long addr',
                           'unsigned long old_len',
                           'unsigned long new_len',
                           'unsigned long flags',
                           'unsigned long new_addr'],
                  'number': '25',
                  'name': 'sys_mremap'},
                 {'args': [], 'number': '24', 'name': 'sys_sched_yield'},
                 {'args': ['int n',
                           'fd_set *inp',
                           'fd_set *outp',
                           'fd_set*exp',
                           'struct timeval *tvp'],
                  'number': '23',
                  'name': 'sys_select'},
                 {'args': ['int *filedes'], 'number': '22', 'name': 'sys_pipe'},
                 {'args': ['const char *filename', 'int mode'],
                  'number': '21',
                  'name': 'sys_access'},
                 {'args': ['unsigned long fd',
                           'const struct iovec *vec',
                           'unsigned long vlen'],
                  'number': '20',
                  'name': 'sys_writev'},
                 {'args': ['unsigned long fd',
                           'const struct iovec *vec',
                           'unsigned long vlen'],
                  'number': '19',
                  'name': 'sys_readv'},
                 {'args': ['unsigned int fd', 'const char *buf', 'size_t count', 'loff_t pos'],
                  'number': '18',
                  'name': 'sys_pwrite64'},
                 {'args': ['unsigned long fd', 'char *buf', 'size_t count', 'loff_t pos'],
                  'number': '17',
                  'name': 'sys_pread64'},
                 {'args': ['unsigned int fd', 'unsigned int cmd', 'unsigned long arg'],
                  'number': '16',
                  'name': 'sys_ioctl'},
                 {'args': ['unsigned long __unused'],
                  'number': '15',
                  'name': 'sys_rt_sigreturn'},
                 {'args': ['int how', 'sigset_t *nset', 'sigset_t *oset', 'size_t sigsetsize'],
                  'number': '14',
                  'name': 'sys_rt_sigprocmask'},
                 {'args': ['int sig',
                           'const struct sigaction *act',
                           'struct sigaction *oact',
                           'size_t sigsetsize'],
                  'number': '13',
                  'name': 'sys_rt_sigaction'},
                 {'args': ['unsigned long brk'], 'number': '12', 'name': 'sys_brk'},
                 {'args': ['unsigned long addr', 'size_t len'],
                  'number': '11',
                  'name': 'sys_munmap'},
                 {'args': ['unsigned long start', 
                           'size_t len', 
                           'unsigned long prot'],
                  'number': '10',
                  'name': 'sys_mprotect'},
                 {'args': ['unsigned long addr',
                           'unsigned long len',
                           'unsigned long prot',
                           'unsigned long flags',
                           'unsigned long fd',
                           'unsigned long off'],
                  'number': '9',
                  'name': 'sys_mmap'},
                 {'args': ['unsigned int fd', 
                           'off_t offset', 
                           'unsigned int origin'],
                  'number': '8',
                  'name': 'sys_lseek'},
                 {'args': ['struct poll_fd *ufds', 
                           'unsigned int nfds', 
                           'long timeout_msecs'],
                  'number': '7',
                  'name': 'sys_poll'},
                 {'args': ['fconst char *filename', 'struct stat *statbuf'],
                  'number': '6',
                  'name': 'sys_lstat'},
                 {'args': ['unsigned int fd', 'struct stat *statbuf'],
                  'number': '5',
                  'name': 'sys_fstat'},
                 {'args': ['const char *filename', 'struct stat *statbuf'],
                  'number': '4',
                  'name': 'sys_stat'},
                 {'args': ['unsigned int fd'], 
                  'number': '3', 'name': 'sys_close'},
                 {'args': ['const char *filename', 'int flags', 'int mode'],
                  'number': '2',
                  'name': 'sys_open'},
                 {'args': ['unsigned int fd', 
                           'const char *buf', 
                           'size_t count'],
                  'number': '1',
                  'name': 'sys_write'},
                 {'args': ['unsigned int fd', 'char *buf', 'size_t count'],
                  'number': '0',
                  'name': 'sys_read'}]

